"""Agrega fase transicion de usuarios visitantes

Revision ID: 60a73ff1e0f4
Revises: 74b0733ecf08
Create Date: 2026-05-31 09:12:49.294778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60a73ff1e0f4'
down_revision: Union[str, Sequence[str], None] = '74b0733ecf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_visitante', sa.Column('fase_transicion', mysql.TINYINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_visitante', 'fase_transicion')
    # ### end Alembic commands ###
