"""Amplicar precision scores a rango negativo para mejora en la logica del backend

Revision ID: 74b0733ecf08
Revises: e1b0a75cd65e
Create Date: 2026-05-30 19:36:31.598359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74b0733ecf08'
down_revision: Union[str, Sequence[str], None] = 'e1b0a75cd65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metrica_establecimiento', 'score_contenido_base',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.DECIMAL(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('metrica_establecimiento', 'score_colaborativo_base',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.DECIMAL(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('recomendacion_generada', 'score_contenido_usado',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.DECIMAL(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('recomendacion_generada', 'score_colaborativo_usado',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.DECIMAL(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('recomendacion_generada_historico', 'score_contenido_usado',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.DECIMAL(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('recomendacion_generada_historico', 'score_colaborativo_usado',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.DECIMAL(precision=6, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recomendacion_generada_historico', 'score_colaborativo_usado',
               existing_type=sa.DECIMAL(precision=6, scale=4),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('recomendacion_generada_historico', 'score_contenido_usado',
               existing_type=sa.DECIMAL(precision=6, scale=4),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('recomendacion_generada', 'score_colaborativo_usado',
               existing_type=sa.DECIMAL(precision=6, scale=4),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('recomendacion_generada', 'score_contenido_usado',
               existing_type=sa.DECIMAL(precision=6, scale=4),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('metrica_establecimiento', 'score_colaborativo_base',
               existing_type=sa.DECIMAL(precision=6, scale=4),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('metrica_establecimiento', 'score_contenido_base',
               existing_type=sa.DECIMAL(precision=6, scale=4),
               type_=mysql.DECIMAL(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
