"""Add solicita_baja and id_establecimiento_padre

Revision ID: ae6ef78344dd
Revises: 60a73ff1e0f4
Create Date: 2026-06-02 16:40:25.453238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6ef78344dd'
down_revision: Union[str, Sequence[str], None] = '60a73ff1e0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establecimiento', sa.Column('solicita_baja', sa.Boolean(), nullable=False))
    op.add_column('establecimiento', sa.Column('id_establecimiento_padre', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'establecimiento', 'establecimiento', ['id_establecimiento_padre'], ['id_establecimiento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'establecimiento', type_='foreignkey')
    op.drop_column('establecimiento', 'id_establecimiento_padre')
    op.drop_column('establecimiento', 'solicita_baja')
    # ### end Alembic commands ###
