"""Estructura inicial completa EkiSystem

Revision ID: e1b0a75cd65e
Revises: e1785d8860ce
Create Date: 2026-05-20 22:23:07.135553

"""
from typing import Sequence, Union

# pyrefly: ignore [missing-import]
from alembic import op
# pyrefly: ignore [missing-import]
import sqlalchemy as sa
# pyrefly: ignore [missing-import]
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1b0a75cd65e'
down_revision: Union[str, Sequence[str], None] = 'e1785d8860ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_categoria_padre', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('icono', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_padre'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cluster_establecimiento',
    sa.Column('id_cluster', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_cluster', sa.String(length=100), nullable=True),
    sa.Column('centroide', sa.JSON(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('total_establecimientos', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cluster')
    )
    op.create_table('cluster_usuario',
    sa.Column('id_cluster', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_cluster', sa.String(length=100), nullable=True),
    sa.Column('centroide', sa.JSON(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('total_usuarios', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cluster')
    )
    op.create_table('etiqueta',
    sa.Column('id_etiqueta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_etiqueta'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('interaccion_usuario_historico',
    sa.Column('id_interaccion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('tipo_interaccion', sa.String(length=30), nullable=True),
    sa.Column('peso_interaccion', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('id_sesion', sa.String(length=36), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_interaccion')
    )
    op.create_table('pais',
    sa.Column('id_pais', sa.CHAR(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_pais')
    )
    op.create_table('rango_informador',
    sa.Column('id_rango', mysql.TINYINT(), autoincrement=True, nullable=False),
    sa.Column('nivel', mysql.TINYINT(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('puntos_minimos', sa.Integer(), nullable=False),
    sa.Column('factor_confianza', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color_badge', sa.CHAR(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id_rango'),
    sa.UniqueConstraint('nivel')
    )
    op.create_table('recomendacion_generada_historico',
    sa.Column('id_recomendacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('categoria_recomendacion', sa.String(length=50), nullable=True),
    sa.Column('posicion', mysql.TINYINT(), nullable=True),
    sa.Column('score_total', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_contenido_usado', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_colaborativo_usado', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_boost_aplicado', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('distancia_km', sa.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('radio_usado_km', mysql.TINYINT(), nullable=True),
    sa.Column('fallback_nivel', mysql.TINYINT(), nullable=True),
    sa.Column('razon_principal', sa.String(length=50), nullable=True),
    sa.Column('detalle_razon', sa.String(length=200), nullable=True),
    sa.Column('estrategia_usada', sa.String(length=20), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('fue_clickeada', sa.Boolean(), nullable=True),
    sa.Column('fecha_click', sa.DateTime(), nullable=True),
    sa.Column('es_descubrimiento', sa.Boolean(), nullable=True),
    sa.Column('diversity_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id_recomendacion')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.Enum('masculino', 'femenino', 'otro', 'prefiero_no_decir'), nullable=True),
    sa.Column('tipo_usuario', sa.Enum('visitante', 'propietario', 'admin'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administrador',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nivel_admin', mysql.TINYINT(), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('dispositivo_usuario',
    sa.Column('id_dispositivo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_dispositivo', sa.Enum('movil', 'tablet', 'escritorio', 'desconocido'), nullable=False),
    sa.Column('sistema_operativo', sa.String(length=50), nullable=True),
    sa.Column('es_ultimo', sa.Boolean(), nullable=False),
    sa.Column('fecha_deteccion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_dispositivo')
    )
    op.create_table('estado_geo',
    sa.Column('id_estado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pais', sa.CHAR(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id_pais'], ),
    sa.PrimaryKeyConstraint('id_estado')
    )
    op.create_table('usuario_visitante',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rango', mysql.TINYINT(), nullable=True),
    sa.Column('id_cluster', sa.Integer(), nullable=True),
    sa.Column('puntos_experiencia', sa.Integer(), nullable=True),
    sa.Column('puntos_reputacion', sa.Integer(), nullable=True),
    sa.Column('perfil_completado', sa.Boolean(), nullable=False),
    sa.Column('fecha_ultima_actividad', sa.DateTime(), nullable=True),
    sa.Column('radio_busqueda_km', mysql.TINYINT(), nullable=True),
    sa.Column('vector_preferencias', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_cluster'], ['cluster_usuario.id_cluster'], ),
    sa.ForeignKeyConstraint(['id_rango'], ['rango_informador.id_rango'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('municipio',
    sa.Column('id_municipio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado_geo.id_estado'], ),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_table('preferencia_usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('peso', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_visitante.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_categoria')
    )
    op.create_table('sesion_usuario',
    sa.Column('id_sesion', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('total_vistas', sa.Integer(), nullable=True),
    sa.Column('id_dispositivo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivo_usuario.id_dispositivo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index('idx_sesion_usuario_fecha', 'sesion_usuario', ['id_usuario', 'fecha_inicio'], unique=False)
    op.create_table('usuario_propietario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=True),
    sa.Column('documento_verificacion', sa.String(length=500), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_visitante.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('colonia',
    sa.Column('id_colonia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipio.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_colonia')
    )
    op.create_table('ubicacion_usuario',
    sa.Column('id_ubicacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('precision_metros', sa.Integer(), nullable=True),
    sa.Column('id_sesion', sa.String(length=36), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion_usuario.id_sesion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_index('idx_ubicacion_usuario_fecha', 'ubicacion_usuario', ['id_usuario', 'fecha_registro'], unique=False)
    op.create_table('establecimiento',
    sa.Column('id_establecimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('direccion_texto', sa.String(length=500), nullable=True),
    sa.Column('id_colonia', sa.Integer(), nullable=True),
    sa.Column('id_cluster', sa.Integer(), nullable=True),
    sa.Column('vector_caracteristicas', sa.JSON(), nullable=True),
    sa.Column('tipo_establecimiento', sa.Enum('restaurante', 'local', 'puesto_informal'), nullable=False),
    sa.Column('es_informal', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', 'suspendido'), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('id_usuario_registro', sa.Integer(), nullable=False),
    sa.Column('id_admin_aprobacion', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('total_resenas', sa.Integer(), nullable=True),
    sa.Column('calificacion_promedio', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_admin_aprobacion'], ['administrador.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_cluster'], ['cluster_establecimiento.id_cluster'], ),
    sa.ForeignKeyConstraint(['id_colonia'], ['colonia.id_colonia'], ),
    sa.ForeignKeyConstraint(['id_usuario_registro'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_establecimiento')
    )
    op.create_index('idx_establecimiento_colonia', 'establecimiento', ['id_colonia'], unique=False)
    op.create_index('idx_establecimiento_estado_activo', 'establecimiento', ['estado', 'es_activo'], unique=False)
    op.create_table('contribucion_informacion',
    sa.Column('id_contribucion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=True),
    sa.Column('tipo_contribucion', sa.Enum('nuevo_lugar', 'edicion_info', 'nueva_foto', 'nuevo_platillo', 'nueva_resena'), nullable=False),
    sa.Column('descripcion_cambio', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado'), nullable=False),
    sa.Column('id_admin_revision', sa.Integer(), nullable=True),
    sa.Column('fecha_contribucion', sa.DateTime(), nullable=False),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('puntos_otorgados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin_revision'], ['administrador.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_visitante.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_contribucion')
    )
    op.create_index('idx_contribucion_usuario_estado', 'contribucion_informacion', ['id_usuario', 'estado'], unique=False)
    op.create_table('establecimiento_categoria',
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.PrimaryKeyConstraint('id_establecimiento', 'id_categoria')
    )
    op.create_table('establecimiento_etiqueta',
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiqueta.id_etiqueta'], ),
    sa.PrimaryKeyConstraint('id_establecimiento', 'id_etiqueta')
    )
    op.create_table('favorito_guardado',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('fecha_guardado', sa.DateTime(), nullable=False),
    sa.Column('nota_personal', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_visitante.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_establecimiento')
    )
    op.create_table('horario',
    sa.Column('id_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('dia_semana', mysql.TINYINT(), nullable=False),
    sa.Column('hora_apertura', sa.Time(), nullable=True),
    sa.Column('hora_cierre', sa.Time(), nullable=True),
    sa.Column('cerrado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.PrimaryKeyConstraint('id_horario'),
    sa.UniqueConstraint('id_establecimiento', 'dia_semana', name='uq_horario_estab_dia')
    )
    op.create_table('imagen',
    sa.Column('id_imagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.Enum('exterior', 'interior', 'platillo', 'menu', 'otro'), nullable=False),
    sa.Column('id_usuario_upload', sa.Integer(), nullable=False),
    sa.Column('fecha_upload', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado'), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario_upload'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('interaccion_usuario',
    sa.Column('id_interaccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('tipo_interaccion', sa.Enum('vista_detalle', 'guardado_favorito', 'compartido', 'llamada_telefono', 'abrir_maps', 'resena_dejada', 'ruta_calculada'), nullable=False),
    sa.Column('peso_interaccion', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('id_sesion', sa.String(length=36), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion_usuario.id_sesion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_interaccion')
    )
    op.create_index('idx_interaccion_estab_fecha', 'interaccion_usuario', ['id_establecimiento', 'fecha'], unique=False)
    op.create_index('idx_interaccion_usuario_fecha', 'interaccion_usuario', ['id_usuario', 'fecha'], unique=False)
    op.create_table('local_comercial',
    sa.Column('id_local', sa.Integer(), nullable=False),
    sa.Column('numero_local', sa.String(length=20), nullable=True),
    sa.Column('nivel_piso', sa.String(length=10), nullable=True),
    sa.Column('nombre_edificio', sa.String(length=200), nullable=True),
    sa.Column('tiene_area_comedor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_local'], ['establecimiento.id_establecimiento'], ),
    sa.PrimaryKeyConstraint('id_local')
    )
    op.create_table('metrica_establecimiento',
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('score_contenido_base', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_colaborativo_base', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('boost_proximidad_zona', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('boost_informal', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('score_boost_combinado', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('popularidad_7d', sa.Integer(), nullable=True),
    sa.Column('popularidad_30d', sa.Integer(), nullable=True),
    sa.Column('polaridad_promedio', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.PrimaryKeyConstraint('id_establecimiento')
    )
    op.create_table('platillo',
    sa.Column('id_platillo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('id_usuario_registro', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario_registro'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_platillo')
    )
    op.create_table('propietario_establecimiento',
    sa.Column('id_propietario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado'), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('id_admin_aprobacion', sa.Integer(), nullable=True),
    sa.Column('documento_prueba', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_admin_aprobacion'], ['administrador.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_propietario'], ['usuario_propietario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_propietario', 'id_establecimiento')
    )
    op.create_table('puesto_informal',
    sa.Column('id_puesto', sa.Integer(), nullable=False),
    sa.Column('es_movil', sa.Boolean(), nullable=False),
    sa.Column('ubicacion_referencia', sa.Text(), nullable=True),
    sa.Column('dias_tipicos', sa.String(length=100), nullable=True),
    sa.Column('horario_aproximado', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_puesto'], ['establecimiento.id_establecimiento'], ),
    sa.PrimaryKeyConstraint('id_puesto')
    )
    op.create_table('recomendacion_generada',
    sa.Column('id_recomendacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('categoria_recomendacion', sa.Enum('cercania', 'popularidad_zona', 'preferencia_contenido', 'colaborativo_cluster', 'cold_start', 'descubrimiento', 'tendencia_informal'), nullable=False),
    sa.Column('posicion', mysql.TINYINT(), nullable=False),
    sa.Column('score_total', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_contenido_usado', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_colaborativo_usado', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('score_boost_aplicado', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('distancia_km', sa.DECIMAL(precision=8, scale=3), nullable=True),
    sa.Column('radio_usado_km', mysql.TINYINT(), nullable=False),
    sa.Column('fallback_nivel', mysql.TINYINT(), nullable=False),
    sa.Column('razon_principal', sa.Enum('preferencia_categoria', 'historial_similar', 'popular_zona', 'colaborativo', 'cluster_similar', 'cercano', 'cold_start', 'descubrimiento', 'tendencia_informal'), nullable=True),
    sa.Column('detalle_razon', sa.String(length=200), nullable=True),
    sa.Column('estrategia_usada', sa.Enum('contenido', 'colaborativo', 'cold_start', 'hibrido', 'cluster', 'popularidad', 'serendipia'), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('fue_clickeada', sa.Boolean(), nullable=False),
    sa.Column('fecha_click', sa.DateTime(), nullable=True),
    sa.Column('es_descubrimiento', sa.Boolean(), nullable=False),
    sa.Column('diversity_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recomendacion')
    )
    op.create_index('idx_recomendacion_usuario_categoria', 'recomendacion_generada', ['id_usuario', 'categoria_recomendacion', 'fecha_generacion'], unique=False)
    op.create_index('idx_recomendacion_usuario_estab', 'recomendacion_generada', ['id_usuario', 'id_establecimiento'], unique=False)
    op.create_table('reporte',
    sa.Column('id_reporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('tipo_reporte', sa.Enum('informacion_incorrecta', 'lugar_cerrado', 'contenido_inapropiado', 'spam', 'otro'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'resuelto', 'descartado'), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=False),
    sa.Column('id_admin_resolucion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin_resolucion'], ['administrador.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    op.create_table('resena',
    sa.Column('id_resena', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('calificacion', mysql.TINYINT(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_resena', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado'), nullable=False),
    sa.Column('id_admin_revision', sa.Integer(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('polaridad', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('subjetividad', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('procesado_nlp', sa.Boolean(), nullable=False),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='ck_resena_calificacion'),
    sa.ForeignKeyConstraint(['id_admin_revision'], ['administrador.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_resena'),
    sa.UniqueConstraint('id_usuario', 'id_establecimiento', name='uq_resena_usuario_estab')
    )
    op.create_index('idx_resena_estab_estado', 'resena', ['id_establecimiento', 'estado'], unique=False)
    op.create_index('idx_resena_procesado_nlp', 'resena', ['procesado_nlp'], unique=False)
    op.create_table('restaurante',
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('id_categoria_principal', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('acepta_reservaciones', sa.Boolean(), nullable=False),
    sa.Column('servicio_domicilio', sa.Boolean(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('sitio_web', sa.String(length=500), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('precio_promedio', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_principal'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_restaurante'], ['establecimiento.id_establecimiento'], ),
    sa.PrimaryKeyConstraint('id_restaurante')
    )
    op.create_table('historial_visita',
    sa.Column('id_visita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_establecimiento', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.String(length=36), nullable=True),
    sa.Column('fecha_visita', sa.DateTime(), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('fue_recomendado', sa.Boolean(), nullable=False),
    sa.Column('id_recomendacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_establecimiento'], ['establecimiento.id_establecimiento'], ),
    sa.ForeignKeyConstraint(['id_recomendacion'], ['recomendacion_generada.id_recomendacion'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion_usuario.id_sesion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_visita')
    )
    op.create_index('idx_historial_usuario_estab_fecha', 'historial_visita', ['id_usuario', 'id_establecimiento', 'fecha_visita'], unique=False)
    op.create_index('idx_historial_usuario_fecha', 'historial_visita', ['id_usuario', 'fecha_visita'], unique=False)
    op.create_table('log_puntos',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Enum('contribucion_aprobada', 'resena_aprobada', 'foto_aprobada', 'nuevo_lugar', 'penalizacion', 'subida_rango'), nullable=False),
    sa.Column('id_contribucion', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_contribucion'], ['contribucion_informacion.id_contribucion'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario_visitante.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_puntos')
    op.drop_index('idx_historial_usuario_fecha', table_name='historial_visita')
    op.drop_index('idx_historial_usuario_estab_fecha', table_name='historial_visita')
    op.drop_table('historial_visita')
    op.drop_table('restaurante')
    op.drop_index('idx_resena_procesado_nlp', table_name='resena')
    op.drop_index('idx_resena_estab_estado', table_name='resena')
    op.drop_table('resena')
    op.drop_table('reporte')
    op.drop_index('idx_recomendacion_usuario_estab', table_name='recomendacion_generada')
    op.drop_index('idx_recomendacion_usuario_categoria', table_name='recomendacion_generada')
    op.drop_table('recomendacion_generada')
    op.drop_table('puesto_informal')
    op.drop_table('propietario_establecimiento')
    op.drop_table('platillo')
    op.drop_table('metrica_establecimiento')
    op.drop_table('local_comercial')
    op.drop_index('idx_interaccion_usuario_fecha', table_name='interaccion_usuario')
    op.drop_index('idx_interaccion_estab_fecha', table_name='interaccion_usuario')
    op.drop_table('interaccion_usuario')
    op.drop_table('imagen')
    op.drop_table('horario')
    op.drop_table('favorito_guardado')
    op.drop_table('establecimiento_etiqueta')
    op.drop_table('establecimiento_categoria')
    op.drop_index('idx_contribucion_usuario_estado', table_name='contribucion_informacion')
    op.drop_table('contribucion_informacion')
    op.drop_index('idx_establecimiento_estado_activo', table_name='establecimiento')
    op.drop_index('idx_establecimiento_colonia', table_name='establecimiento')
    op.drop_table('establecimiento')
    op.drop_index('idx_ubicacion_usuario_fecha', table_name='ubicacion_usuario')
    op.drop_table('ubicacion_usuario')
    op.drop_table('colonia')
    op.drop_table('usuario_propietario')
    op.drop_index('idx_sesion_usuario_fecha', table_name='sesion_usuario')
    op.drop_table('sesion_usuario')
    op.drop_table('preferencia_usuario')
    op.drop_table('municipio')
    op.drop_table('usuario_visitante')
    op.drop_table('estado_geo')
    op.drop_table('dispositivo_usuario')
    op.drop_table('administrador')
    op.drop_table('usuario')
    op.drop_table('recomendacion_generada_historico')
    op.drop_table('rango_informador')
    op.drop_table('pais')
    op.drop_table('interaccion_usuario_historico')
    op.drop_table('etiqueta')
    op.drop_table('cluster_usuario')
    op.drop_table('cluster_establecimiento')
    op.drop_table('categoria')
    # ### end Alembic commands ###
